/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Born': '出生',
    'Borrow money. Buy animals, at least two of each species. Wait for them to breed. Sell some. Buy other animals. Pay back your debt before the cumulative interest gets too high. Be patient. Get badges. Reset after a while to get a special bonus. (Click this to hide it.': '借钱。 购买动物，每个物种至少两只。 等待它们繁殖。 卖一些。 买其他动物。 在累计利息过高之前偿还债务。 耐心一点。 获取徽章。 稍后重设以获得特殊奖励。 （点击此按钮将其隐藏。',
    'Pay': '支付',
    'Stats': '统计',
    'Sold': '出售',
    'Export': '导出',
    'For Animal Exchange': '动物交流',
    'I accept': '我同意',
    'Import': '导入',
    'Animals (': '动物 (',
    'Achievements (': '成就 (',
    'Borrow': '贷款',
    'Max': '最大',
    'Loading...': '加载中...',
    'price boosts': '价格上涨',
    'Reset': '重置',
    'Get a Bigger Enclosure: (': '获得一个更大的栅栏: (',
    'Get a Higher Birth Rate: (': '获得一个更高的出生率: (',
    'Get Higher Prices: (': '获得更高的价格: (',
    'Get visitors more frequently for $': '让游客更频繁地前来参观 花费 $',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "A ": "一只 ",
    "50 ": "",
    "You maxed out the price of your ": "你把价格提高到了最高，为你的 ",
    "You bought a ": "你购买了一只 ",
    "Buy 1: $": "购买 1: $",
    "Sell 1: $": "出售 1: $",
    "You sold 100,000 ": "你出售了 100,000 ",
    "You sold 10,000 ": "你出售了 10,000 ",
    "You sold 1,000 ": "你出售了 1,000 ",
    "You sold 100 ": "你出售了 100 ",
    "You sold 1 ": "你出售了 1 ",
    "20 times you bought bigger enclosures for your ": "你购买了20倍大的围栏，为了你的 ",
    "10 times you bought bigger enclosures for your ": "你购买了10倍大的围栏，为了你的 ",
    "100,000 ": "100,000 ",
    "10,000 ": "10,000 ",
    "1,000 ": "1,000 ",
    "100 ": "100 ",
    "You maxed out the birth-rate of your ": "出生率达到了极限，你的",
    "You got 100,000 ": "你有100,000只 ",
    "You got 10,000 ": "你有10,000只 ",
    "You got 1,000 ": "你有1000只 ",
    "You got 100 ": "你有100只 ",
    "You got 1 ": "你有1只 ",
    "You bought 100 ": "你购买了100只 ",
    "You bought 200 ": "你购买了200只 ",
    "You bought 500 ": "你购买了500只 ",
    "You bought 1,000 ": "你购买了1,000只 ",
    "You bought 10,000 ": "你购买了10,000只 ",
    "You bought 100,000 ": "你购买了100,000只 ",
    "You bought 10 price boosts for your ": "你购买了价格上涨 10 为了你的 ",
    "You bought 10 death-rate reductions for your ": "你购买了死亡率降低 10 为了你的 ",
    "You bought 10 birth-rate boosts for your ": "你购买了出生率提高 10 为了你的 ",
    "You minimized the death-rate of your ": "您最大程度地降低了死亡率，为了你的 ",
    'otters': '水獭',
    'Otters': '水獭',
    'Otter': '水獭',
    'peacocks': '孔雀',
    'Peacocks': '孔雀',
    'Peacock': '孔雀',
    'penguins': '企鹅',
    'Penguins': '企鹅',
    'Penguin': '企鹅',
    'snakes': '蛇',
    'Snakes': '蛇',
    'Snake': '蛇',
    'beavers': '海狸',
    'Beavers': '海狸',
    'Beaver': '海狸',
    'flamingos': '火烈鸟',
    'Flamingos': '火烈鸟',
    'Flamingo': '火烈鸟',
    'meerkats': '猫鼬',
    'Meerkats': '猫鼬',
    'Meerkat': '猫鼬',
    'tapirs': '貘',
    'Tapirs': '貘',
    'Tapir': '貘',
    'Tapir': '貘',
    'turtles': '乌龟',
    'Turtles': '乌龟',
    'Turtle': '乌龟',
    'chameleons': '变色龙',
    'Chameleons': '变色龙',
    'Chameleon': '变色龙',
    'crocodiles': '鳄鱼',
    'Crocodiles': '鳄鱼',
    'Crocodile': '鳄鱼',
    'monkeys': '猴子',
    'Monkeys': '猴子',
    'Monkey': '猴子',
    'anteaters': '食蚁兽',
    'Anteaters': '食蚁兽',
    'Anteater': '食蚁兽',
    'kangaroos': '袋鼠',
    'Kangaroos': '袋鼠',
    'Kangaroo': '袋鼠',
    'seals': '海豹',
    'Seals': '海豹',
    'Seal': '海豹',
    'bears': '熊',
    'Bears': '熊',
    'Bear': '熊',
    'zebras': '斑马',
    'Zebras': '斑马',
    'Zebra': '斑马',
    'antelopes': '羚羊',
    'Antelopes': '羚羊',
    'Antelope': '羚羊',
    'eagles': '鹰',
    'Eagles': '鹰',
    'Eagle': '鹰',
    'okapis': '㺢㹢狓',
    'Okapis': '㺢㹢狓',
    'Okapi': '㺢㹢狓',
    'ostriches': '鸵鸟',
    'Ostriches': '鸵鸟',
    'Ostriche': '鸵鸟',
    'Ostrich': '鸵鸟',
    'condors': '秃鹰',
    'Condors': '秃鹰',
    'Condor': '秃鹰',
    'orcas': '逆戟鲸',
    'Orcas': '逆戟鲸',
    'Orca': '逆戟鲸',
    'pandas': '熊猫',
    'Pandas': '熊猫',
    'Panda': '熊猫',
    'lions': '狮子',
    'Lions': '狮子',
    'Lion': '狮子',
    'tigers': '老虎',
    'Tigers': '老虎',
    'Tiger': '老虎',
    'wolves': '狼',
    'Wolves': '狼',
    'Wolve': '狼',
    'Wolf': '狼',
    'sharks': '鲨鱼',
    'Sharks': '鲨鱼',
    'Shark': '鲨鱼',
    'rhinos': '犀牛',
    'Rhinos': '犀牛',
    'Rhino': '犀牛',
    'dolphins': '海豚',
    'Dolphins': '海豚',
    'Dolphin': '海豚',
    'giraffes': '长颈鹿',
    'Giraffes': '长颈鹿',
    'Giraffe': '长颈鹿',
    'gorillas': '大猩猩',
    'Gorillas': '大猩猩',
    'Gorilla': '大猩猩',
    'hippos': '河马',
    'Hippos': '河马',
    'Hippo': '河马',
    'jaguars': '美洲虎',
    'Jaguars': '美洲虎',
    'Jaguar': '美洲虎',
    "times you bought bigger enclosures for your ": "次你买了更大的围栏为你的 ",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " were born": " 出生了",
    " died": " 死掉了",
    " in your Zoo": " 在你的动物园里",
    " for your Zoo": " 为你的动物园",
    " was born in your Zoo": " 出生在了你的动物园",
    " from your Zoo": " 从你的动物园",
    " died in your Zoo": " 死在了你的动物园里",
    " was born": " 出生",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^\| Buy (.+) \|$/, '\| 购买 $1 \|'],
    [/^Buy (.+) \|$/, '购买 $1 \|'],
    [/^\| Sell (.+) \|$/, '\| Sell $1 \|'],
    [/^Sell (.+) \|$/, 'Sell $1 \|'],
    [/^Time played: (.+) seconds$/, '游戏时长：$1 秒'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);